- name: make sure that Apache is installed
  yum:
    name: "{{ package_name }}"
    update_cache: yes
    state: latest

- name: Make sure that Apache is Running
  service:
    name: "{{ service_name }}"
    enabled: yes
    state: started
